### PR TITLE
Use common .ci -> 1.x as we are doing with rest of plugins.

### PR DESCRIPTION
**Pull request by mashhurs**
### Description
Align on common `.ci` -> `1.x` branch as a standard (other plugins also use).

### Author's checklist
- [x] Run CI after merging following PR and backporting into `1.x` branch: https://github.com/logstash-plugins/.ci/pull/70/files
- [x] Bakckport (cherry pick) this change to `8.x` branch: https://github.com/elastic/logstash-filter-elastic_integration/pull/195

### CODE REVIEW

**Review by donoghuc — APPROVED** [review]
👍

**Review by robbavey — DISMISSED** [review]
LGTM, after other PR is merged

**Comment by mashhurs** [comment]
Build with main is 🟢 https://buildkite.com/elastic/logstash-filter-elastic-integration-build/builds/445
This change needs to be backported to `8.x`.

**Review by donoghuc — APPROVED** [review]
💚

**Pull request merged**
