### PR TITLE
bump elasticsearch tree branch to 8.15

### PR DESCRIPTION
**Pull request by jsvd**
bumping to 8.15 increases reduces code rot and puts the project in a better place to keep up with ES code changes.
Also with the merge of https://github.com/elastic/elasticsearch/commit/2a6ad970487458d43584830ba7463baaef75306d the jar produced for this plugin no longer triggers any security warnings in scanners like grype:

```
logstash-filter-elastic_integration [change_branch_8_15]
❯ grype -q ./build/libs/logstash-filter-elastic_integration-0.1.12-all.jar
No vulnerabilities found
```

### CODE REVIEW

**Comment by jsvd** [comment]
@logstashmachine bump patch

**Comment by jsvd** [comment]
@logstashmachine bump patch

**Review by yaauie — APPROVED** [review]
👍🏼

**Comment by jsvd** [comment]
this was missing a version bump, I'll added  it in a separate PR, https://github.com/elastic/logstash-filter-elastic_integration/pull/157

**Pull request merged**
