### PR TITLE
Add a PR backporter

### PR DESCRIPTION
**Pull request by mashhurs**
### Description

This PR adds a PR backporter which we need to backport changes to designated base branches when we merge PRs to target branches.

### CODE REVIEW

**Comment by mashhurs** [comment]
> Is there a reason we can just use an off the shelf solution for backport? https://github.com/tibdex/backport seems to be the most popular.

We have a common script in LS core for this purpose: https://github.com/elastic/logstash/blob/main/devtools/backport
I am open to use https://github.com/tibdex/backport or any other new tool but it may require extra processes/effort. For example, our devtools backlporter is fully automated, creates label and attaches to the PR. As I do see with https://github.com/tibdex/backport, we need to manually create label or automate it by converting current python code into nodejs?! (just checked high level details). `tibdex/backport` seems simplified interactions with the GH API, where we are directly using them in our backporter.

**Do you have any concerns with the LS core devtool/backporter?**

Honestly, I haven't seen any pain points so far with LS core backporter. If we have, I would support migrating all LS core and other plugin backporters (if we have) altogether.

**Review by donoghuc — APPROVED** [review]
My only concern  apart from general maintainability issues using our own script vs consuming a popular one is copying around files that need updates in the body https://github.com/elastic/logstash-filter-elastic_integration/pull/203/files#diff-38840c5e92fffb039a64f7632661853ab0075df02cb3f3dc123f1de961936a27R100 

I'm fine with just doing this for now while we evaluate benefits of using a pre built action :)

**Comment by mashhurs** [comment]
> My only concern apart from general maintainability issues using our own script vs consuming a popular one is copying around files that need updates in the body https://github.com/elastic/logstash-filter-elastic_integration/pull/203/files#diff-38840c5e92fffb039a64f7632661853ab0075df02cb3f3dc123f1de961936a27R100
> 
> I'm fine with just doing this for now while we evaluate benefits of using a pre built action :)

Ah from that perspective makes sense. Let me create a placeholder to push forward. For now I am not seeing its urgency or broken features, it is nice to have tech dept!

**Comment by mashhurs** [comment]
@logstashmachine backport 8.x

**Comment by mashhurs** [comment]
@logstashmachine backport 8.x

**Pull request merged**
