### PR TITLE
id->event bridge: handle array types as lists

### PR DESCRIPTION
**Pull request by yaauie**
Fixes issue where a Java array is present on an ingest document by mapping the values back to a List:

~~~
[[main]>worker0] EventProcessor - exception processing event: Missing Converter handling for full class name=[Ljava.lang.String;, simple name=String[]
~~~

### CODE REVIEW

**Review by mashhurs — APPROVED** [review]
LGTM

**Comment by yaauie** [comment]
I'll get a changelog and version bump in, then get this merged.

**Review by mashhurs — DISMISSED** [review]
LGTM!

**Review by mashhurs — APPROVED** [review]
lgtm ❤️

**Pull request merged**
