### PR TITLE
Make GeoIpDatabaseProvider#build public to accommodate JRuby package-private method visibility

### PR DESCRIPTION
**Pull request by jsvd**
Fix for CI failure at runtime: https://buildkite.com/elastic/logstash-serverless-integration-testing/builds/299#018de5b0-39b0-49f3-a295-d15475281758/1258-1265

likely due to  JRuby 9.4.6.0 change:

* Starting with Java 17, package-private methods will no longer be bound automatically even if they can be made visible. [#8061](https://github.com/jruby/jruby/issues/8061), [#8093](https://github.com/jruby/jruby/pull/8093)

https://github.com/jruby/jruby/pull/8093

### CODE REVIEW

**Comment by yaauie** [comment]
Good catch. We will need a changelog entry and a version bump. Release can likely wait until we have a feature or get closer to a release of Logstash that includes the affected Jruby.

**Comment by jsvd** [comment]
@logstashmachine bump patch

**Comment by jsvd** [comment]
@logstashmachine bump patch

**Comment by jsvd** [comment]
> Good catch. We will need a changelog entry and a version bump. Release can likely wait until we have a feature or get closer to a release of Logstash that includes the affected Jruby.

@yaauie done! If possible I'd rather publish this ASAP as it's breaking current integration tests with Logstash main (already on 9.4.6.0).

**Review by yaauie — APPROVED** [review]

**Pull request merged**
